CREATE TABLE IF NOT EXISTS ik_users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NULL,
  display_name VARCHAR(100) NOT NULL,
  role ENUM('FAN', 'CREATOR', 'ADMIN') NOT NULL DEFAULT 'FAN',
  grade ENUM('S', 'A', 'B', 'C') NOT NULL DEFAULT 'C',
  profile_image VARCHAR(500) NULL,
  instagram_id VARCHAR(100) NULL,
  youtube_url VARCHAR(500) NULL,
  bio TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ik_creators (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NULL,
  slug VARCHAR(120) NOT NULL UNIQUE,
  display_name VARCHAR(100) NOT NULL,
  handle VARCHAR(100) NOT NULL,
  bio TEXT NOT NULL,
  category VARCHAR(80) NOT NULL DEFAULT 'creator',
  platform VARCHAR(80) NOT NULL DEFAULT 'Instagram',
  avatar_url VARCHAR(500) NOT NULL,
  cover_url VARCHAR(500) NOT NULL,
  instagram_id VARCHAR(100) NULL,
  youtube_url VARCHAR(500) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ik_creators_user FOREIGN KEY (user_id) REFERENCES ik_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ik_payment_orders (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_no VARCHAR(80) NOT NULL UNIQUE,
  creator_id INT UNSIGNED NOT NULL,
  fan_user_id INT UNSIGNED NULL,
  supporter_name VARCHAR(100) NOT NULL,
  supporter_email VARCHAR(190) NULL,
  message TEXT NULL,
  amount INT UNSIGNED NOT NULL,
  payment_provider VARCHAR(40) NOT NULL DEFAULT 'NICEPAY',
  payment_key VARCHAR(190) NULL,
  status ENUM('PENDING_PAYMENT', 'PAID', 'CANCELLED', 'REFUNDED') NOT NULL DEFAULT 'PENDING_PAYMENT',
  commission_rate DECIMAL(5,2) NOT NULL DEFAULT 25.00,
  admin_fee INT UNSIGNED NOT NULL DEFAULT 0,
  creator_payout INT UNSIGNED NOT NULL DEFAULT 0,
  payout_status ENUM('PENDING', 'SENT', 'FAILED') NOT NULL DEFAULT 'PENDING',
  paid_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ik_orders_creator FOREIGN KEY (creator_id) REFERENCES ik_creators(id),
  CONSTRAINT fk_ik_orders_fan FOREIGN KEY (fan_user_id) REFERENCES ik_users(id) ON DELETE SET NULL,
  INDEX idx_ik_orders_creator_status (creator_id, status),
  INDEX idx_ik_orders_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ik_admin_settings (
  setting_key VARCHAR(80) PRIMARY KEY,
  setting_value VARCHAR(500) NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ik_admin_settings (setting_key, setting_value)
VALUES ('commission_rate', '25')
ON DUPLICATE KEY UPDATE setting_key = setting_key;
